[package]
name = "boardswarm-protocol"
version = "0.0.1"
edition = "2021"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
license = "MIT OR Apache-2.0"
description = "Boardswarm protobuf protocol definitions"
repository = "https://github.com/boardswarm/boardswarm"
readme = "README.md"

[dependencies]
bytes = "1.7.1"
futures = "0.3.25"
prost = "0.12.1"
prost-types = "0.12.1"
serde = { version = "1.0.189", features = ["derive"] }
tokio = { version = "1.30.0", features = ["full"] }
tonic = "0.11"

[build-dependencies]
prost-build = "0.12.1"
prost-wkt-build = "0.5.0"
tonic-build = "0.11"

[dev-dependencies]
serde_json = "1.0.91"
