[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
{ id = "RUSTSEC-2023-0071", reason = "No patch is available." }
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "Unicode-3.0",
    "Zlib"
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["Apache-2.0", "ISC", "OpenSSL"], crate = "aws-lc-sys" },
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-root-certs" },
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [ ]
deny = [
  { crate = "webpki-roots", reason = "Should only use native certs" },
  { crate = "ring", reason = "rustls#1877 - multiple rustls backend can cause panics" },
  { crate = "openssl", reason = "Avoid multiple tls implementations" }
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
