[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [ ]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "WTFPL",
    "Zlib"
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
    { allow = ["Unicode-DFS-2016"], crate = "finl_unicode" },
    { allow = ["Unicode-DFS-2016"], crate = "wezterm-bidi" },
    { allow = ["OpenSSL"], crate = "ring" },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
{ path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [ ]
deny = [
  { crate = "webpki-roots", reason = "Should only use native certs" },
  { crate = "aws-lc-rs", reason = "rustls#1877 - multiple rustls backend can cause panics" },
  { crate = "openssl", reason = "Avoid multiple tls implementations" }
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
