[package]
name = "boardswarm-client"
version = "0.0.1"
edition = "2021"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
license = "MIT OR Apache-2.0"
description = "Boardswarm client library"
repository = "https://github.com/boardswarm/boardswarm"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
bytes = "1.4.0"
futures = "0.3.25"
boardswarm-protocol = { version = "0.0.1", path = "../boardswarm-protocol" }
tokio = { version = "1.30.0", features = ["full"] }
tonic = { version = "0.12.3", features = ["tls", "tls-native-roots"] }
tracing = "0.1.37"
thiserror = "1.0.40"
tower = "0.5"
http = "1.1.0"
serde = "1.0.189"
http-serde = "2.1"
serde_yaml = "0.9.25"
oauth2 = "5.0.0-alpha.4"
reqwest = { version = "0.12", features = ["json"] }
async-trait = "0.1.74"
url = { version = "2.4.1", features = ["serde"] }
