syntax = "proto3";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
package boardswarm;

service Boardswarm {
  rpc LoginInfo(google.protobuf.Empty) returns (LoginInfoList);

  rpc List(ItemTypeRequest) returns (ItemList);
  rpc Monitor(ItemTypeRequest) returns (stream ItemEvent);
  rpc ItemProperties(ItemPropertiesRequest) returns (ItemPropertiesMsg);

  rpc DeviceInfo (DeviceRequest) returns (stream Device);
  rpc DeviceChangeMode(DeviceModeRequest) returns (google.protobuf.Empty);

  rpc ActuatorChangeMode(ActuatorModeRequest) returns (google.protobuf.Empty);

  rpc ConsoleConfigure (ConsoleConfigureRequest) returns (google.protobuf.Empty);
  rpc ConsoleStreamOutput (ConsoleOutputRequest) returns (stream ConsoleOutput);
  rpc ConsoleStreamInput (stream ConsoleInputRequest) returns (google.protobuf.Empty);

  rpc VolumeInfo(VolumeRequest) returns (VolumeInfoMsg);
  rpc VolumeIo (stream VolumeIoRequest) returns (stream VolumeIoReply);

  // Commit all data in an uploader specific manner; e.g. may trigger a USB reset for DFU devices
  rpc VolumeCommit(VolumeRequest) returns (google.protobuf.Empty);
  // Erase all data of target
  rpc VolumeErase(VolumeEraseRequest) returns (google.protobuf.Empty);

  // Set a media stream, can be audio or video
  rpc MediaSetup(stream MediaRequest) returns (stream SignalMessage);

  // Set up a stream to a keyboard
  rpc KeyboardIo(stream KeyboardRequest) returns (stream KeyboardState);

  // Set up a stream to a mouse
  rpc MouseIo(stream MouseRequest) returns (google.protobuf.Empty);

}

message OidcInfo {
        string url = 1;
        string clientId = 2;
}

message LoginInfo {
   string description = 1;
   oneof method {
        OidcInfo oidc = 2;
   }
}

message LoginInfoList {
  repeated LoginInfo info = 1;
}

enum ItemType {
  ITEM_TYPE_DEVICE = 0;
  ITEM_TYPE_CONSOLE = 1;
  ITEM_TYPE_ACTUATOR = 2;
  ITEM_TYPE_VOLUME = 3;
  // audio/video streaming
  ITEM_TYPE_MEDIA = 4;
  // Emulating external keyboard
  ITEM_TYPE_KEYBOARD = 5;
  // Emulating external mouse
  ITEM_TYPE_MOUSE = 6;
}

message ItemTypeRequest {
  ItemType type = 1;
}

message Item {
  uint64 id = 1;
  string name = 2;
  optional string instance = 3;
}

message ItemList {
  repeated Item item = 1;
}

message ItemEvent {
   oneof event {
     ItemList add = 1;
     uint64 remove = 2;
   }
}

message ItemPropertiesRequest {
  ItemType type = 1;
  uint64 item = 2;
}

message Property {
  string key = 1;
  string value = 2;
}

message ItemPropertiesMsg {
   repeated Property property = 1;
}

message DeviceRequest {
  uint64 device = 1;
}

message Device {
  repeated Console consoles = 1;
  repeated Volume volumes = 2;
  repeated Mode modes = 3;
  optional string current_mode = 4;
  repeated Media media = 5;
}

message Console {
  string name = 1;
  optional uint64 id = 2;
}

message Volume {
  string name = 1;
  optional uint64 id = 2;
}

message Media {
  string name = 1;
  optional uint64 id = 2;
}

message Mode {
  string name = 1;
  optional string depends = 2;
  bool available = 3;
}

message DeviceModeRequest {
  uint64 device = 1;
  string mode = 2;
}

message ConsoleConfigureRequest {
  uint64 console = 1;
  google.protobuf.Struct parameters = 2;
}

message ConsoleInputRequest {
  oneof TargetOrData {
    uint64 console = 1;
    bytes data = 2;
  }
}

message ConsoleOutputRequest {
   uint64 console = 1;
}

message ConsoleOutput {
   bytes data = 1;
}

message ActuatorModeRequest {
  uint64 actuator = 1;
  google.protobuf.Struct parameters = 2;
}

message VolumeTarget {
  string name = 1;
  bool readable = 2;
  bool writable = 3;
  bool seekable = 4;
  /// target size in bytes if known
  optional uint64 size = 5;
  /// blocksize of the underlying media; For optimal performance read/write request should be done
  /// at that size
  optional uint32 blocksize = 6;
}

message VolumeInfoMsg {
   repeated VolumeTarget target = 1;
   /// Whether the list of target is exhaustive. If false there may be more
   /// valid names then listend
   bool exhaustive = 2;
}

message VolumeRequest {
  uint64 volume = 1;
}

message VolumeEraseRequest {
  uint64 volume = 1;
  string target = 2;
}

message VolumeIoTarget {
  uint64 volume = 1;
  string target = 2;
  optional uint64 length = 3;
}

message VolumeIoTargetReply {
  VolumeTarget target = 1;
}

message VolumeIoRead {
  uint64 length = 1;
  uint64 offset = 2;
}

message VolumeIoReadReply {
  bytes data = 1;
}

message VolumeIoWrite {
  bytes data = 1;
  uint64 offset = 2;
}

message VolumeIoWriteReply {
  uint64 written = 1;
}

message VolumeIoFlush {
}

message VolumeIoFlushReply {
}

message VolumeIoShutdown {
}

message VolumeIoShutdownReply {
}

message VolumeIoRequest {
  oneof TargetOrRequest {
     VolumeIoTarget target = 1;
     VolumeIoRead read = 2;
     VolumeIoWrite write = 3;
     VolumeIoFlush flush = 4;
     VolumeIoShutdown shutdown = 5;
  }
}

// Each IO request has a matching reply
message VolumeIoReply {
  oneof Reply {
        VolumeIoTargetReply target = 1;
        VolumeIoReadReply read = 2;
        VolumeIoWriteReply write = 3;
        VolumeIoFlushReply flush = 4;
        VolumeIoShutdownReply shutdown = 5;
  }
}

// The first message should be the media item to start negotiation with,
// everything after that are signal messages 
message MediaRequest {
  oneof ItemOrSignal {
    uint64 item = 1;
    SignalMessage signal = 2;
  }
}

message SignalMessageSdp {
  string sdp = 1;
}

message SignalMessageIceCandidate {
  string candidate = 1;
  uint32 mline_index = 2;
}

message SignalMessage {
  oneof SdpMessage {
    SignalMessageSdp offer = 1;
    SignalMessageSdp answer = 2;
    SignalMessageIceCandidate ice = 3;
  }
}

message KeyboardRequest {
  oneof ItemOrSignal {
    uint64 item = 1;
    KeyboardEvent event = 2;
  }
}

enum KeyboardEventType{
  KeyDown = 0;
  KeyUp = 1;
}

message KeyboardEvent {
  KeyboardEventType type = 1;
  // 8 bit Key value per Keyboard/Keypad  usage id's of the HID
  // Usage Tables see: https://www.usb.org/document-library/hid-usage-tables-17
  //
  // Depending on the provider there may be a limit to the amount of keys that
  // can be pressed at the same time
  uint32 key = 2;
}

enum KeyboardLed {
  KEYBOARD_LED_NUM_LOCK = 0;
  KEYBOARD_LED_CAPS_LOCK = 1;
  KEYBOARD_LED_SCROLL_LOCK = 2;
  KEYBOARD_LED_COMPOSE = 3;
  KEYBOARD_LED_KANA = 4;
}

message KeyboardState  {
   // List of leds that are *on*
  repeated KeyboardLed led = 1;
}

message MouseRequest {
  oneof ItemOrSignal {
    uint64 item = 1;
    MouseInput input = 2;
  }
}

message MouseInput {
  // buttons bitmask, 0 - 7
  uint32 buttons = 1;
  // x value 0 - 32767
  uint32 x = 2;
  // y value 0 - 32767
  uint32 y = 3;
  // vert. wheel, 8 bits signed
  sint32 wheel = 4;
  // horiz. wheel, 8 bits signed
  sint32 hwheel = 5;
}

