name: test suite

env:
  GITHUB_TAG: ghcr.io/${{ github.repository }}

on:
  push:
    branches-ignore:
        - "gh-readonly-queue/**"
  pull_request:
  merge_group:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.70"
      - run: cargo test --all-targets --all-features

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.70"
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.70"
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings

  minimal-dependencies:
    name: minimal direct dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "nightly-2024-01-01"
          components: clippy
      - run: cargo check -Z direct-minimal-versions

  docker-image:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_IMAGE }}
          tags: |
            "type=ref,event=branch"
            "type=ref,suffix=-{{sha}},event=branch"
            "type=ref,suffix=-{{date 'YYYYMMDD'}},event=branch"
            "type=ref,event=tag"
            "type=ref,event=pr"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile

  allgreen:
    if: always()
    needs:
    - test
    - fmt
    - clippy
    - minimal-dependencies
    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
