// WebRTC glue code for Boardswarm media streaming
// Manages RTCPeerConnection instances, bridging Rust/WASM callbacks with browser WebRTC APIs.

const sessions = [];

/**
 * Create an RTCPeerConnection and attach it to the given video element.
 * Returns a numeric handle for subsequent calls.
 *
 * @param {string} videoElementId - ID of the <video> element to attach streams to
 * @returns {number} handle
 */
export function webrtc_create(videoElementId) {
    const pc = new RTCPeerConnection({
        iceServers: [{ urls: "stun:stun.l.google.com:19302" }],
    });

    const session = {
        pc,
        videoElementId,
        onIce: null,
        onConnected: null,
        onError: null,
    };

    pc.ontrack = (event) => {
        if (event.streams && event.streams[0]) {
            const video = document.getElementById(videoElementId);
            if (video) {
                video.srcObject = event.streams[0];
                video.play().catch((e) => console.warn("autoplay blocked:", e));
            }
        }
    };

    pc.onicecandidate = (event) => {
        if (event.candidate && session.onIce) {
            session.onIce(
                event.candidate.candidate,
                event.candidate.sdpMLineIndex ?? 0,
            );
        }
    };

    pc.onconnectionstatechange = () => {
        const state = pc.connectionState;
        if (state === "connected" && session.onConnected) {
            session.onConnected();
        } else if (
            (state === "failed" || state === "closed") &&
            session.onError
        ) {
            session.onError("Connection " + state);
        }
    };

    const handle = sessions.length;
    sessions.push(session);
    return handle;
}

/**
 * Register a callback for local ICE candidates generated by the RTCPeerConnection.
 * The callback receives (candidate: string, mlineIndex: number).
 *
 * @param {number} handle
 * @param {Function} callback
 */
export function webrtc_on_ice(handle, callback) {
    const session = sessions[handle];
    if (session) session.onIce = callback;
}

/**
 * Register a callback invoked when the WebRTC connection reaches the "connected" state.
 *
 * @param {number} handle
 * @param {Function} callback
 */
export function webrtc_on_connected(handle, callback) {
    const session = sessions[handle];
    if (session) session.onConnected = callback;
}

/**
 * Apply a remote SDP offer, create an answer, and return the answer SDP via callback.
 * The on_answer callback receives (answerSdp: string).
 *
 * @param {number} handle
 * @param {string} offerSdp
 * @param {Function} onAnswer
 */
export function webrtc_set_offer(handle, offerSdp, onAnswer) {
    const session = sessions[handle];
    if (!session) return;
    const pc = session.pc;

    pc.setRemoteDescription({ type: "offer", sdp: offerSdp })
        .then(() => pc.createAnswer())
        .then((answer) => {
            return pc.setLocalDescription(answer).then(() => answer);
        })
        .then((answer) => {
            onAnswer(answer.sdp);
        })
        .catch((e) => {
            console.error("webrtc_set_offer failed:", e);
            if (session.onError) session.onError("offer handling failed: " + e);
        });
}

/**
 * Add a remote ICE candidate received from the server.
 *
 * @param {number} handle
 * @param {string} candidate
 * @param {number} mlineIndex
 */
export function webrtc_add_ice(handle, candidate, mlineIndex) {
    const session = sessions[handle];
    if (!session) return;

    session.pc
        .addIceCandidate({ candidate, sdpMLineIndex: mlineIndex })
        .catch((e) => console.warn("addIceCandidate failed:", e));
}

/**
 * Close the RTCPeerConnection and release resources.
 *
 * @param {number} handle
 */
export function webrtc_dispose(handle) {
    const session = sessions[handle];
    if (session) {
        session.pc.close();
        sessions[handle] = null;
    }
}

/**
 * Enter "fill window" mode by moving the video element into a top-level
 * <dialog> modal. The dialog is appended to document.body so it escapes
 * any parent CSS stacking context (transform, will-change, overflow, etc.)
 * that would otherwise constrain position:fixed children.
 *
 * A close button is injected into the dialog. Clicking it (or pressing Esc)
 * restores the video to its original DOM position.
 *
 * @param {string} videoElementId
 */
export function webrtc_enter_fill(videoElementId) {
    if (document.getElementById("webrtc-fill-dialog")) return; // already open

    const video = document.getElementById(videoElementId);
    if (!video) return;

    // Build the modal dialog
    const dialog = document.createElement("dialog");
    dialog.id = "webrtc-fill-dialog";
    dialog.style.cssText =
        "margin:0;padding:0;border:none;" +
        "width:100vw;height:100vh;max-width:100%;max-height:100%;" +
        "background:#000;display:flex;align-items:center;justify-content:center;" +
        "overflow:hidden;";

    // Inject a style for the ::backdrop pseudo-element
    const backdropStyle = document.createElement("style");
    backdropStyle.id = "webrtc-fill-backdrop-style";
    backdropStyle.textContent =
        "#webrtc-fill-dialog::backdrop { background: #000; }";
    document.head.appendChild(backdropStyle);

    // Close button inside the dialog (pure JS — no Dioxus involvement)
    const closeBtn = document.createElement("button");
    closeBtn.textContent = "✕";
    closeBtn.style.cssText =
        "position:absolute;top:1rem;right:1rem;" +
        "background:rgba(0,0,0,0.6);color:#fff;border:none;border-radius:4px;" +
        "padding:0.4rem 0.8rem;cursor:pointer;font-size:1.2rem;line-height:1;z-index:1;";
    closeBtn.onclick = () => webrtc_exit_fill(videoElementId);

    // Dismiss on Esc (dialog default) too
    dialog.addEventListener("cancel", () => webrtc_exit_fill(videoElementId));

    // Remember where the video lives so we can restore it
    video._fillParent = video.parentNode;
    video._fillNext = video.nextSibling;
    video._fillStyle = video.getAttribute("style") || "";

    // Style the video for full-coverage inside the dialog
    video.style.cssText =
        "width:100%;height:100%;object-fit:contain;display:block;";

    dialog.appendChild(closeBtn);
    dialog.appendChild(video);
    document.body.appendChild(dialog);
    dialog.showModal();
}

/**
 * Exit "fill window" mode: restore the video to its original DOM position
 * and remove the dialog.
 *
 * @param {string} videoElementId
 */
export function webrtc_exit_fill(videoElementId) {
    const dialog = document.getElementById("webrtc-fill-dialog");
    const backdropStyle = document.getElementById("webrtc-fill-backdrop-style");
    const video = document.getElementById(videoElementId);

    if (video && video._fillParent) {
        // Restore to original position in the DOM
        video._fillParent.insertBefore(video, video._fillNext || null);
        // Restore original inline style
        if (video._fillStyle) {
            video.setAttribute("style", video._fillStyle);
        } else {
            video.removeAttribute("style");
        }
        video._fillParent = null;
        video._fillNext = null;
        video._fillStyle = null;
    }

    if (dialog) {
        dialog.close();
        dialog.remove();
    }
    if (backdropStyle) backdropStyle.remove();
}

