// WebRTC glue code for Boardswarm media streaming
// Manages RTCPeerConnection instances, bridging Rust/WASM callbacks with browser WebRTC APIs.

const sessions = [];

/**
 * Create an RTCPeerConnection and attach it to the given video element.
 * Returns a numeric handle for subsequent calls.
 *
 * @param {string} videoElementId - ID of the <video> element to attach streams to
 * @returns {number} handle
 */
export function webrtc_create(videoElementId) {
    const pc = new RTCPeerConnection({
        iceServers: [{ urls: "stun:stun.l.google.com:19302" }],
    });

    // Suppress native browser media controls on the video element.
    const video = document.getElementById(videoElementId);
    if (video) {
        video.disablePictureInPicture = true;
        video.setAttribute("controlslist", "nodownload nofullscreen noremoteplayback");
    }

    const session = {
        pc,
        videoElementId,
        onIce: null,
        onConnected: null,
        onError: null,
    };

    pc.ontrack = (event) => {
        if (event.streams && event.streams[0]) {
            const video = document.getElementById(videoElementId);
            if (video) {
                video.srcObject = event.streams[0];
                video.play().catch((e) => console.warn("autoplay blocked:", e));
            }
        }
    };

    pc.onicecandidate = (event) => {
        if (event.candidate && session.onIce) {
            session.onIce(
                event.candidate.candidate,
                event.candidate.sdpMLineIndex ?? 0,
            );
        }
    };

    pc.onconnectionstatechange = () => {
        const state = pc.connectionState;
        if (state === "connected" && session.onConnected) {
            session.onConnected();
        } else if (
            (state === "failed" || state === "closed") &&
            session.onError
        ) {
            session.onError("Connection " + state);
        }
    };

    const handle = sessions.length;
    sessions.push(session);
    return handle;
}

/**
 * Register a callback for local ICE candidates generated by the RTCPeerConnection.
 * The callback receives (candidate: string, mlineIndex: number).
 *
 * @param {number} handle
 * @param {Function} callback
 */
export function webrtc_on_ice(handle, callback) {
    const session = sessions[handle];
    if (session) session.onIce = callback;
}

/**
 * Register a callback invoked when the WebRTC connection reaches the "connected" state.
 *
 * @param {number} handle
 * @param {Function} callback
 */
export function webrtc_on_connected(handle, callback) {
    const session = sessions[handle];
    if (session) session.onConnected = callback;
}

/**
 * Apply a remote SDP offer, create an answer, and return the answer SDP via callback.
 * The on_answer callback receives (answerSdp: string).
 *
 * @param {number} handle
 * @param {string} offerSdp
 * @param {Function} onAnswer
 */
export function webrtc_set_offer(handle, offerSdp, onAnswer) {
    const session = sessions[handle];
    if (!session) return;
    const pc = session.pc;

    pc.setRemoteDescription({ type: "offer", sdp: offerSdp })
        .then(() => pc.createAnswer())
        .then((answer) => {
            return pc.setLocalDescription(answer).then(() => answer);
        })
        .then((answer) => {
            onAnswer(answer.sdp);
        })
        .catch((e) => {
            console.error("webrtc_set_offer failed:", e);
            if (session.onError) session.onError("offer handling failed: " + e);
        });
}

/**
 * Add a remote ICE candidate received from the server.
 *
 * @param {number} handle
 * @param {string} candidate
 * @param {number} mlineIndex
 */
export function webrtc_add_ice(handle, candidate, mlineIndex) {
    const session = sessions[handle];
    if (!session) return;

    session.pc
        .addIceCandidate({ candidate, sdpMLineIndex: mlineIndex })
        .catch((e) => console.warn("addIceCandidate failed:", e));
}

/**
 * Close the RTCPeerConnection and release resources.
 *
 * @param {number} handle
 */
export function webrtc_dispose(handle) {
    const session = sessions[handle];
    if (session) {
        session.pc.close();
        sessions[handle] = null;
    }
}


